name: DeathSwap
version: 1.0
main: com.jeffkmeng.minecraft.deathswap.DeathSwap
commands:
  deathswap:
    description: Manage the death swap game
    usage: "for usage info: /deathswap help"
    permission: deathswap.manage
permissions:
  deathswap.manage:
    description: Start, stop, and manage death swap
    default: OP